### ISSUE TITLE
Add support for windows with hidden activity bar

### ISSUE THREAD

**Issue by IgorKrupenja** [lehni/vscode-titlebar-less-macos#1]
Would be great if there was support for windows with hidden activity bar. Right now it looks like this:

![image](https://user-images.githubusercontent.com/26354715/43026218-691ea3c2-8c7d-11e8-9a7f-656df425594f.png)

For some inspiration, there were some pretty nice screens in this comment https://github.com/Microsoft/vscode/issues/12377#issuecomment-249358040

**Comment by lehni** [comment]
Oh yeah, I never use it in this mode so I didn't notice! I'll see what can be done.

**Comment by lehni** [comment]
@krupenja I've published 1.0.3 now that addresses all these. Please note that you should disable first before upgrading. If that doesn't work, then you need to reinstall VSCode. I've improved the way that restoration of patches files is handled now.

**Comment by lehni** [comment]
PS: I managed to implement all 3 scenarios exactly as outline by @orta in https://github.com/Microsoft/vscode/issues/12377#issuecomment-249358040

**Comment by IgorKrupenja** [comment]
@lehni So fast, I'm impressed! 💪 Thank you. Do you think the " Please note that you should disable first before upgrading" should be added to the readme?

**Comment by lehni** [comment]
@krupenja you're right. I've addressed it now!

**Comment by burknator** [comment]
I have a similar problem when the activity bar is disabled and the sidebar is hidden. Is there a way to fix this for myself? Oh and thanks a bunch for the extension, I live that look!

<img width="450" alt="bildschirmfoto 2018-07-31 um 12 28 35" src="https://user-images.githubusercontent.com/26658/43454422-42f5d790-94bd-11e8-8a9a-40324f0e97e8.png">

**Comment by lehni** [comment]
@burknator that's strange, it works for me. What version of VSCode and the extension are you using?

![screen shot 2018-07-31 at 13 24 35](https://user-images.githubusercontent.com/213275/43456805-21a93d04-94c5-11e8-9534-70cbf1e5f5a4.png)

**Comment by burknator** [comment]
@lehni Sorry, forgot to mention that I disabled tabs. 

VS Code: 1.25.1
Your extension: 1.3.3

**Comment by lehni** [comment]
@burknator you are right. Reopening...

**Comment by lehni** [comment]
Fix released in v1.4.0

**Comment by burknator** [comment]
@lehni Wow that was fast! Thanks a Lot!

**Comment by lehni** [comment]
You're welcome! Glad you like it. Please let me know how it works for you :)

**Comment by burknator** [comment]
Yes, works perfectly!
