### ISSUE TITLE
VS Code Insiders: Enabling Titlebar-Less breaks custom titlebar style

### ISSUE THREAD

**Issue by lumaxis** [lehni/vscode-titlebar-less-macos#10]
Reporting another issue in Insiders 🙂 

With today's update, enabling the extension breaks the application of `"window.titleBarStyle": "custom",` and shows the native titlebar instead:

<img width="397" alt="screenshot 2018-07-26 18 06 22" src="https://user-images.githubusercontent.com/406937/43274151-a1e93660-90fe-11e8-9fc7-adf33f6f471d.png">

If I disable the extension again, the custom style is applied correctly again.

**Comment by lehni** [comment]
Took me a while to figure this one out, but there's the culprit:

https://github.com/electron/electron/blob/f9e2ec43d0688a95610796e01501f5f882eb3bb7/docs/api/breaking-changes.md#breaking-api-changes-20
