### ISSUE TITLE
Unable to apply all patches (0/4) - macOS 10.14 Beta (18A336e)

### ISSUE THREAD

**Issue by alinchiuaru** [lehni/vscode-titlebar-less-macos#11]
Whenever I tried to run the `Titlebar-Less: Enable` command it throws the above error.
Doesn't get fixed by closing and opening the app again.

Maybe it's something small you can look into. 
Love the way this looks, great job!

**Comment by lehni** [comment]
Hmm, maybe you may have to run the app with admin rights in order to apply the patches? I don't have macOS 10.14 Beta installed, so I can't test. Or maybe you can change the owner of the full VSCode app to you own user?

**Comment by alinchiuaru** [comment]
Same result, tried to run with `sudo code` from terminal as the root user but no luck.

**Comment by lehni** [comment]
Can you try running it in this way:

```sh
sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"
```

**Comment by lehni** [comment]
Note that you only need to do this once to apply the patches. Once this worked, quit the application and start it normally as non-root again.

**Comment by lehni** [comment]
I think `sudo code` won't work, because it will spawn the app in another process, probably as non-root.

**Comment by alinchiuaru** [comment]
Did the above and it partially worked. I got:` Unable to apply all patches (2/4)`

**Comment by lehni** [comment]
Very strange... I think it has to do with the security updates in macOS 10.14. I can't tell you how to circumvent them as I don't have it installed myself yet. I'll look into this once it stops being beta, but maybe others can figure this out before?

**Comment by alinchiuaru** [comment]
Sure thing. Thank you either way! 👍

**Comment by lehni** [comment]
BTW, what version of VSCode are you running?

**Comment by alinchiuaru** [comment]
Just realised something: I was using the Insiders version (Version 1.23.0-insider (1.23.0-insider))

Just tested the above (`sudo "/Applications/Visual Studio Code.app/Contents/MacOS/Electron"`) with the regular VSCode (Version 1.25.1 (1.25.1)) and it works fine.

**Comment by lehni** [comment]
Great news! You should be able to also use it with the latest insiders version (1.26.0-insider).

The patches will have to change over time and only need to be applied once per version, so I can only ever support the latest versions I think.
