### ISSUE TITLE
Empty space before tabs in second/third/etc splits when side bar is closed

### ISSUE THREAD

**Issue by IgorKrupenja** [lehni/vscode-titlebar-less-macos#12]
Steps:
1. Launch VSCode with Titlebar-less plugin enabled.
2. Close side bar.
3. Open at least two splits.

There is an empty space between tabs in 2nd/3rd splits.
![image](https://user-images.githubusercontent.com/26354715/43684352-49fe1726-98a7-11e8-9bda-c6b372dcb1df.png)

**Comment by lehni** [comment]
Oh damn :) I'll take a look soon Hope it's not a show-stopper until then.

**Comment by lehni** [comment]
@krupenja hmm, I can't reproduce this. Did you update to the latest version of the extension? You have to reapply by running the `Titlebar-Less: Enable` command again, and then restart.

**Comment by IgorKrupenja** [comment]
@lehni The thing is that trackpad and keyboard died on my Mac *again* yesterday and I have decided to move to Linux for good. So I have no Mac machine to test anymore - I guess we can close this for now; at least until someone else can reproduce the issue.
