### ISSUE TITLE
Full screen issue with action bar set to display on the right

### ISSUE THREAD

**Issue by wsloth** [lehni/vscode-titlebar-less-macos#14]
I have my action bar set to the right (good old VS2017 feeling), and this causes this extension to reserve space on the left that is not used:
<img width="301" alt="screen shot 2018-08-17 at 15 05 43" src="https://user-images.githubusercontent.com/4933907/44267578-1a1beb00-a22f-11e8-8e38-b6e65ae3364a.png">

On windowed this extension looks awesome. Thanks for the work!

**Comment by wsloth** [comment]
Awesome, thanks for the fix. Can you bump the version and release it into the extension marketplace? Eagerly awaiting it 👍

**Comment by lehni** [comment]
@wsloth I've published it now. Apologies for the delay, I was busy traveling for work last week.
