### ISSUE TITLE
Unable to apply all patches (0/4)

### ISSUE THREAD

**Issue by LukasBombach** [lehni/vscode-titlebar-less-macos#17]
Hey there!

Awesome plugin, this is just what I wanted.

I added the options 

```json
{
    "window.nativeTabs": false,
    "window.titleBarStyle": "custom",
}
```

and ran

`>Titlebar-Less: Enable`

But then I got an error saying

> Unable to apply all patches (0/4)

Do you have any clue from this what could have gone wrong?

**Comment by fabiospampinato** [comment]
@LukasBombach have you tried running VSC with sudo? https://github.com/lehni/vscode-titlebar-less-macos#installing-on-macos-1014-mojave

**Comment by LukasBombach** [comment]
Awesome! That worked! Thank you!

(btw i am not on Mojave (I'm on High Sierra), but that did it for me)

**Comment by LukasBombach** [comment]
PS: Awesome Plugin!

**Comment by fabiospampinato** [comment]
> (btw i am not on Mojave (I'm on High Sierra), but that did it for me)

Yeah I'm on High Sierra too, I don't know why running it with sudo is suddenly a requirement, they must have changed something 🤔

**Comment by LukasBombach** [comment]
I see
