### ISSUE TITLE
Extend the breadcrumb below the semaphore

### ISSUE THREAD

**Issue by fabiospampinato** [lehni/vscode-titlebar-less-macos#18]
I think the breadcrumb should take the full width in this situation:

<img width="864" alt="screen shot 2018-10-09 at 16 09 51" src="https://user-images.githubusercontent.com/1812093/46675022-d960a280-cbdd-11e8-8fcc-0660cc11a392.png">

**Comment by lehni** [comment]
Yeah that makes sense. Do you want to give it a go?

**Comment by fabiospampinato** [comment]
I'm not really using the breadcrumb, I've just found this issue while updating my theme.

But if you can tell me what a fix for this could/should like I can add this to my todo list if you want.

**Comment by lehni** [comment]
I've taken care of it :)

**Comment by fabiospampinato** [comment]
I think you've accidentally extended the tabs bar below the semaphore  too or something. If there are enough tabs that I can scroll them then they go below the semaphore. 

<img width="864" alt="screen shot 2018-10-17 at 21 32 43" src="https://user-images.githubusercontent.com/1812093/47111579-37336100-d254-11e8-9182-6b60f561f7c5.png">

**Comment by lehni** [comment]
Not really accidental, I just wasn't aware that the tabs scroll. There are so many possible combinations of these features, and I only really use about 10% or so... I guess I can keep patching, but in the end what I'm interested in making work are the features that I use myself. Maybe I should just reverse this change as I don't even use breadcrumbs.

**Comment by fabiospampinato** [comment]
Yeah I guess maintaining an extension like this can be painful. I'm not using the breadcrumb either.

Maybe you can keep this issue open and revert the commit in question until somebody "completes" it. Do what you think it's best.

**Comment by lehni** [comment]
I found some time to look into it now. Fixed in 56dff4ed69c9afab36aab1318910cca5ba97f473 😉

**Comment by fabiospampinato** [comment]
Thank you!
