### ISSUE TITLE
Incompatible with some settings

### ISSUE THREAD

**Issue by smockle** [lehni/vscode-titlebar-less-macos#2]
This extension does not have any effect when `"window.titleBarStyle"` is set to `"native"` or when `"window.nativeTabs"` is set to `true`.

As a workaround, set `"window.titleBarStyle"` to `"custom"` and `"window.nativeTabs"` to `false`.

This isn’t really a bug IMO, but it might be worth noting in the README.

**Comment by lehni** [comment]
You're right, thanks!
