### ISSUE TITLE
Not working on 1.30.0

### ISSUE THREAD

**Issue by dmlemos** [lehni/vscode-titlebar-less-macos#20]
Having trouble getting it to work on 1.30.0

After enabling it, the usual message "Your Code installation appears to be corrupt. Please reinstall." appears, but no effect.

**Comment by gee-forr** [comment]
Just installed v1.7.1, still not working. Let me know if I can help debug in any way to figure out what's the problem

**Comment by jtmkrueger** [comment]
So I was having this problem, and decided to see if it was a conflict in my settings. I commented out `"window.nativeFullScreen": false` and things started working for me again.

**Comment by dmlemos** [comment]
@jtmkrueger that's true! It does work with native full screen. Thanks

**Comment by joshuabalfe** [comment]
I was running into this problem, switching off native tabs fixed it for me

**Comment by mediter** [comment]
Ran into the same issue, tried turned off Native Tabs, the issue persists. But the extension seems to be working at this point.

Tried disable this extension, restart, re-enable the extension, restart, same alert.

Titlebar-Less v. 1.7.1
VS Code v. 1.30.2
macOS Mojave v. 10.14.2

**Comment by mediter** [comment]
the alert seems to intentional on Microsoft's part
[Visual Studio Code Frequently Asked Questions](https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported)

> **Installation appears to be corrupt [Unsupported]**
> VS Code does a background check to detect if the installation has been changed on disk and if so, you will see the text '[Unsupported]' in the title bar. This is done since some extensions directly modify (patch) the VS Code product in such a way that is semi-permanent (until the next update) and this can cause hard to reproduce issues. We are not trying to block VS Code patching, but we want to raise awareness that patching VS Code means you are running an unsupported version. Reinstalling VS Code will replace the modified files and silence the warning.

this repo recommends the following extension:

> [VS Code Fix Checksums](https://github.com/lehni/vscode-fix-checksums)

**Comment by dmlemos** [comment]
Closing this in favour of #22
