### ISSUE TITLE
Sidebar width when on the right

### ISSUE THREAD

**Issue by degardinn** [lehni/vscode-titlebar-less-macos#21]
Love the extension! 
Being one of these weirdos who put the side bar on the right (View/Appearance/Move sidebar right), I was thinking that there's no real point in this case for the sidebar to match the width of the traffic lights. It could use the standard 50px width, right?

![image](https://user-images.githubusercontent.com/23199222/50780087-06216600-1270-11e9-8d79-c12203bdb4cc.png)

**Comment by lehni** [comment]
Yes it could... The CSS is already pretty complex though, adding more special cases further increases its complexity. But maybe it's possible to do in a simple way, I'll check
