### ISSUE TITLE
Stuck after upgrade to version 1.31.0 

### ISSUE THREAD

**Issue by Arelav** [lehni/vscode-titlebar-less-macos#22]
Stuck after upgrade to version 1.31.0
After applying `TitlebarLess: enable` and restart Vscode shows an empty screen and I see no way to roll back except to download a new app and replace VScode in Applications folder.

It's also doesn't allow to open Developer Tools

**Comment by Arelav** [comment]
I opened developer tools before enabling and refreshed the window instead restart.
I'm not familiar with the extension codebase and hope it will help to find the problem.
<img width="719" alt="screen shot 2019-02-06 at 21 26 42" src="https://user-images.githubusercontent.com/1059539/52386947-3b2efd00-2a56-11e9-81d2-6718078d28a7.png">

**Comment by benoitwimart** [comment]
Same problem, I downgrade VS Code and block upgrade  to relaunch it.
(Wow, Lehni the guy who made Scriptographer 👍  <3 )

**Comment by rbardini** [comment]
I've fixed my macOS VSCode installation by restoring the `workbench.main.css.orig.1.31.0` and `workbench.main.js.orig.1.31.0` backup files located in `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/`.

**Comment by weierz** [comment]
@rbardini Thanks for your temporary solution! It works, but doesn't work well for me...

![screen shot 2019-02-10 at 23 12 36](https://user-images.githubusercontent.com/14329786/52535452-692f7c80-2d89-11e9-9421-e1461d572593.png)

When I was trying to disable this extension, it showed:

![screen shot 2019-02-10 at 23 16 22](https://user-images.githubusercontent.com/14329786/52535492-012d6600-2d8a-11e9-93f3-ea0d63af3243.png)

I'm quite confusing about this message. 🤔

**Comment by weierz** [comment]
I've found that the owner doesn't watch this repo.  A properly mention may be needed. @lehni

**Comment by lehni** [comment]
I'm watching now. I will check what's going on and hopefully find a solution shortly!

**Comment by lehni** [comment]
Fixed and released in v1.8.0 🎉
