### ISSUE TITLE
Unable applying in 1.32.0-insider

### ISSUE THREAD

**Issue by visualcookie** [lehni/vscode-titlebar-less-macos#23]
While running the enable command, I'm running into an unknown error of `unable to apply patch (2/4)`, even when using `sudo`.

VSCode Version: Insiders

**Comment by lehni** [comment]
Yes, things keep changing, and need adjustments in the extension... I don't always have time to keep up to date with the Insiders version, as that's changing even faster.

**Comment by lehni** [comment]
Fix is released in 1.8.1
