### ISSUE TITLE
Top of explorer sidebar becomes undraggable

### ISSUE THREAD

**Issue by stuible** [lehni/vscode-titlebar-less-macos#24]
Top of explorer sidebar becomes un-draggable after the window is open for some time.  I'm not sure exactly what causes this to happen but it seems to consistently happen to me.  Re-opening the window fixes it.
<img width="434" alt="Screen Shot 2019-03-31 at 2 28 28 PM" src="https://user-images.githubusercontent.com/1476537/55295385-561c4e80-53c1-11e9-829f-b69598225832.png">

**Comment by fabiospampinato** [comment]
This is a bug with Electron, I think it got fixed in v5.

**Comment by lehni** [comment]
I am not 100% certain that this is the case here, @fabiospampinato. The bug you mention affects the top center, not the sides. I will look into this soon.

**Comment by lehni** [comment]
Hmm it works for me, so maybe this only happens when the window is small enough, or the invisible title of it that catches the mouse interaction really large, covering the explorer tab on the side as well?

**Comment by fabiospampinato** [comment]
@lehni I was referring to [this](https://github.com/electron/electron/issues/14529) bug, which affects the top part of the titlebar, not just the center.

**Comment by lehni** [comment]
@fabiospampinato yes I know. What I meant is the center of the top. Watch the video, and you'll see it only fail in the center region of it.
