### ISSUE TITLE
Unable to apply all patches in VSCode 1.33.0

### ISSUE THREAD

**Issue by mrvkino** [lehni/vscode-titlebar-less-macos#25]
In the new version of VSCode 1.33.0 I have the following message:

```
unable to apply all patches (2/4)
```

It did not happen in 1.32.X.

**Comment by Beyarz** [comment]
Got the same issue after updating vscode to 1.33.0

**Comment by renegadevi** [comment]
Same issue.

**Comment by mohouyizme** [comment]
It happened lately after updating VSCODE, I'm currently at version 1.33.0

**Comment by lehni** [comment]
Yes, new versions of VSCode regularly break this extension. I have to change the patching regular expressions, which is normally straight forward, but I don't always have the time to respond immediately. I'll look into it some time this week.

No need for more confirmations of the bug.

**Comment by lehni** [comment]
I'm working on this as we speak, but there was an unusually high change in the codebase between these two versions, rendering the needed adjustments more complex than normal...

**Comment by lehni** [comment]
For those interested, see c80c6909358a421d0a32f8028c4c935e1b185b30 to understand the complexity involved. All this needs to be deducted from the built versions of VSCode, mainly the file `workbench.main.js` inside `Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/`, which currently is one 5.7MB big minifed JS file...

**Comment by lehni** [comment]
Published as v1.9.0

**Comment by lehni** [comment]
Argh, I was testing against Insiders, which has changed again... It works with that now, but not with 1.33.0. Reopening 🤦‍♂️

**Comment by mohouyizme** [comment]
@lehni anyway that was fast, good job!

**Comment by lehni** [comment]
Fixed in v1.9.1 😅

**Comment by awhitty** [comment]
Thank you for fixing! Love this extension :)

**Comment by mohouyizme** [comment]
Thank you!

**Comment by Beyarz** [comment]
Sweet!
