### ISSUE TITLE
Not working with latest release of VSCode

### ISSUE THREAD

**Issue by simonwjackson** [lehni/vscode-titlebar-less-macos#26]
<img width="483" alt="Screen Shot 2019-04-10 at 2 46 10 PM" src="https://user-images.githubusercontent.com/189379/55908570-67264600-5b9f-11e9-9944-527a8bfe4298.png">
<img width="396" alt="Screen Shot 2019-04-10 at 2 45 19 PM" src="https://user-images.githubusercontent.com/189379/55908533-52e24900-5b9f-11e9-97e1-edbe4d8cf5aa.png">

**Comment by lehni** [comment]
Are you sure you've actually updated the extension? This issue was already fixed two days ago, and a new version was released, see #25
