### ISSUE TITLE
Upper half of debug toolbar buttons not clickable 

### ISSUE THREAD

**Issue by IgorKrupenja** [lehni/vscode-titlebar-less-macos#27]
1. Install vscode-titlebar-less-macos (version 1.9.1) and enable titlebar-less, restart VSCode.
2. Start some debug configuration so that debug toolbar appears.
3. Try clicking on any of the debug toolbar buttons (e.g. Stop).

You can successfully click on a button if clicking the lower half of the button. Nothing happens if you click on the upper half. No such problems with titlebar-less disabled.

**Comment by lehni** [comment]
Same as #24, unfortunately a wontfix in this extension. All we can do is wait for Electron to fix it, and the update make its way into VSCode.

**Comment by IgorKrupenja** [comment]
Thanks for clarifying! Based on info in the Electron issue, I was able to come up with an (ugly) workaround:

1. Install and enable your [other extension](https://marketplace.visualstudio.com/items?itemName=lehni.vscode-fix-checksums).
2. Add `"window.title": "."` to VSCode settings
