### ISSUE TITLE
[FEAT. REQ.] Vertical traffic light option possibility?

### ISSUE THREAD

**Issue by apollolux** [lehni/vscode-titlebar-less-macos#28]
Hello! This is a groovy extension for Mac VSCode users and I would like to request the addition of the ability to choose between horizontal and vertical traffic lights if possible, like in the Atom mod screenshot on [this comment](https://github.com/Microsoft/vscode/issues/12377#issuecomment-482936323) in  [@Microsoft/vscode#12377](https://github.com/Microsoft/vscode/issues/12377). What would be the difficulty in adding this feature?

The other screenshot in that comment (the Xcode-style titlebar) is potentially a trivial change with the Custom CSS & JS extension augmenting the current version of this extension, so I'm not nearly as concerned for that one at the moment.

**Comment by lehni** [comment]
I am not sure how this is achieved in Atom. Both apps use Electron, so there probably is a way, but I couldn't find any references to it in a quick search, and I don't have use for this personally. It's already complicated enough to maintain this extension without such additional hacks, (e.g. see: #25), so I don't think this will become a reality...

**Comment by fabiospampinato** [comment]
This is achievable by hiding the controls entirely and recreating them with CSS, IMHO it's not worth the hassle.

**Comment by lehni** [comment]
I see. Yeah that sounds like too much hassle for me to maintain as well. Thanks for clarifying @fabiospampinato
