### ISSUE TITLE
Not able to click certain areas of tabs.

### ISSUE THREAD

**Issue by asilvadesigns** [lehni/vscode-titlebar-less-macos#29]
With this extension enable, I'm not able to click on certain tab areas and the behavior is inconsistent. It seems like a similar problem as #27 but I'm not sure.

Also, clicking on the "x" to close a tab will not work unless I click directly on the "x" glyph.

Awesome extension btw, thanks!

**Comment by lehni** [comment]
Yes, this is the same as #27 and #24. See here: https://github.com/electron/electron/issues/14529
