### ISSUE TITLE
Double click to zoom

### ISSUE THREAD

**Issue by knopp** [lehni/vscode-titlebar-less-macos#30]
First of all, thank you for this extension. It is a game changer. There is one tiny thing that bugs me a bit. Doubleclicking on draggable areas should maximize (zoom) the window. Would this be possible to implement?

**Comment by lehni** [comment]
Lots of thing are possible, and PRs are always welcome :)

**Comment by lehni** [comment]
Something like this should probably work:

```js
const screenSize = electron.screen.getPrimaryDisplay().size
mainWindow.setSize(screenSize.width, screenSize.height, true) // animate
```

Now how to get to these references from the minified VSCode? Not sure!

**Comment by knopp** [comment]
There is better way I think. In browser process there is Window service, which has maximizeWindow() method. It is used on windows to implement the maximize button.

i.e.
``` js
let ws = require("vs/workbench/services/window/electron-browser/windowService")
let instance = <InstantiationService>.createInstance(ws.WindowService)
windowService.maximizeWindow()
```

this maximizes the window (with OS animation and everything). Slightly tricky part is to retrieve the instantiation service

EDIT: Actually, there is `onWindowTitleDoubleClick` method that is even better

**Comment by knopp** [comment]
So, here's a [short javascript](https://gist.github.com/knopp/b7db7a1ffe92d36300e313af2ce6d8b6), which when included using [vscode-custom-css](https://github.com/be5invis/vscode-custom-css) does the trick.

I'm not sure what the best way is to integrate this with the extension, but hopefully it helps.
