### ISSUE TITLE
ZoomLevel

### ISSUE THREAD

**Issue by hipstersmoothie** [lehni/vscode-titlebar-less-macos#4]
When "window.zoomlevel" is set to anything but 0 the traffic light buttons aren't aligned correctly. -1 causes the explorer to overlap them slightly

**Comment by lehni** [comment]
Yeah that is maybe a limitation of this extension that we can't do much about. Or do you have a suggestion how to specify widths in CSS and JS that ignore the zoom level?

**Comment by lehni** [comment]
I've recently switched to defining the traffic light width and height in css variables, and also retrieve their current value for the settings change in JS.

@hipstersmoothie that means that you can override them both using another extension (https://github.com/be5invis/vscode-custom-css), once this version is rolled out, e.g.:

```css
:root {
  --traffic-light-width: 78px;
  --traffic-light-height: 35px;
}
```

That way you can at least control it from one place. 

There may be a way to inject the zoom level setting into CSS and then use it in these calculations.

**Comment by lehni** [comment]
Version 1.0.8 is out, supporting this override now. I think that's the best I can offer here. I hope it's good enough for you:

https://marketplace.visualstudio.com/items/lehni.vscode-titlebar-less-macos/changelog

**Comment by lehni** [comment]
Reopening because I have a better fix coming up.
