### ISSUE TITLE
Maintenance help?

### ISSUE THREAD

**Issue by dpren** [lehni/vscode-titlebar-less-macos#40]
I notice you haven't been maintaining this as actively lately. I understand it's a lot of work to keep up with all the VSCode updates. I'd love to help. Would you be open to adding me as a co-maintainer so we can keep things working if you're busy?

**Comment by lehni** [comment]
Yes, things are very busy at the moment, but should cool down a bit soon again. I'm happy to have co-maintainers. Perhaps as a first step, you could create a PR to fix the current issues, and we can take it from there?

**Comment by dpren** [comment]
Sounds good 👍
