### ISSUE TITLE
Unable to apple all patches 1/4 issue

### ISSUE THREAD

**Issue by lor1x** [lehni/vscode-titlebar-less-macos#43]
I tried it as a root user as well, added the 2 required lines in the settings.json but the extension will still won't work.

![Screen Shot 2019-10-24 at 09 34 00](https://user-images.githubusercontent.com/22913459/67463306-78b5d380-f641-11e9-8f0c-2ac33ead8205.png)

**Comment by weierz** [comment]
@Win1010 Please read: #38, #40, #41 
Apparently, the owner is busy at work. I plan on fixing it in the middle of December.

**Comment by lor1x** [comment]
Hey @willbchang I already did before you commented and noticed the creator of this cool extension was busy till December but I had to put it here

**Comment by weierz** [comment]
@Win1010 for some other reason, I switched to IntelliJ IDEA for web development recently, so I won't fix this issue. I'm sorry.

**Comment by lor1x** [comment]
@willbchang That's fine. When lehni get's free he maybe can fix that :)
