### ISSUE TITLE
Deprecation notice is missing `window.customTitleBarVisibility` config to hide the title bar

### ISSUE THREAD

**Issue by injust** [lehni/vscode-titlebar-less-macos#45]
I followed your instructions at https://github.com/lehni/vscode-titlebar-less-macos/blob/master/README.md#deprecation-notice to set up Apc Customize UI++, but couldn't get the title bar to disappear. I had to additionally configure this setting for it to work:

```json
{
  "window.customTitleBarVisibility": "never"
}
```

It would be great if you could update the README with this!

**Comment by lehni** [comment]
Yeah I noticed this true and already had it changed locally. Thanks for pointing this out again.

**Comment by injust** [comment]
Fixed by https://github.com/lehni/vscode-titlebar-less-macos/commit/850b67783dd1ad054050a2429bcc02fcd51156b6
