### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by hipstersmoothie** [lehni/vscode-titlebar-less-macos#5]
on macOS you can click the title bar to have the window automatically resize to the available screen size. With this extension enabled you there is nowhere to click to make this happen.

**Comment by lehni** [comment]
That's a general limitation of the `titleBarStyle="hidden"`/ `titleBarStyle="hidden-inset"` setting. Other applications have the same _problem_, e.g. the Slack app on Mac, or Tweetbot.

You can opt-click on the green traffic light though, turning it into a plus sign that makes it go to full window size without going fullscreen.
