### ISSUE TITLE
Window is not draggable with activity bar off

### ISSUE THREAD

**Issue by IgorKrupenja** [lehni/vscode-titlebar-less-macos#7]
At the moment the window is not draggable with activity bar off. Some comments in the original VSCode issue suggest using the space around traffic lights icon to be draggable in this case:
https://github.com/Microsoft/vscode/issues/12377#issuecomment-248647471
https://github.com/Microsoft/vscode/issues/12377#issuecomment-248651408

Not sure that this could be easily implemented though.

**Comment by lehni** [comment]
If you have tabs open, you should be able to drag the window by dragging the tab bar (since 1.0.5). I'll see what I can do about the area around the traffic lights.

**Comment by lehni** [comment]
v1.0.6 is out with this fix in.
