### ISSUE TITLE
Sidebar layout broken in latests Insiders release

### ISSUE THREAD

**Issue by lumaxis** [lehni/vscode-titlebar-less-macos#9]
Titlebar-less version: 1.0.9
VS Code version: 1.26.0-insider (90fc7e66e2e10f643871b42f9c0f1f989d0ed221)

Not sure if you want to support the Insiders release but in the latest VS Code - Insiders release, the sidebar layout is pretty badly broken:

<img width="134" alt="screenshot 2018-07-23 13 29 53" src="https://user-images.githubusercontent.com/406937/43074394-5f9aae20-8e7d-11e8-9828-23ce9869ff7c.png">

It works just fine using my exact same settings in the non-Insiders release version 1.25.1

**Comment by lehni** [comment]
Good to know! I'll have a look :)

**Comment by lehni** [comment]
Released in v1.0.11

**Comment by lumaxis** [comment]
Great, thanks for taking care of this so quickly! 🙏

**Comment by gugadev** [comment]
Happen again in latest Insiders release @lehni. I'll test it on the latest stable.

**Edit**: on stable release works as expected. 👍

**Comment by lehni** [comment]
@gugadev that's a separate issue, thank you for spotting it. I am going to open a new issue for this.
